runtime: php55
api_version: 1

handlers:
- url: /.*
  script: web/index.php

#runtime_config:
#  document_root: web

## Uncomment for Cloud SQL
# beta_settings:
#   cloud_sql_instances: "INSTANCE_CONNECTION_NAME"
